# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy Microservices

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Basket.API
      - name: Build & Push Basket.API
        run: |
          docker build -t kapilkaushal24/basket.api:latest \
            -f src/Services/Basket/Basket.API/Dockerfile .
          docker push kapilkaushal24/basket.api:latest

      - name: Deploy Basket.API
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

      # Discount.GRPC
      - name: Build & Push Discount.GRPC
        run: |
          docker build -t kapilkaushal24/discount.grpc:latest \
            -f src/Services/Discount/Discount.GRPC/Dockerfile .
          docker push kapilkaushal24/discount.grpc:latest

      - name: Deploy Discount.GRPC
        run: |
          curl -X POST ${{ secrets.RENDER_DISCOUNT_GRPC_DEPLOY_HOOK_URL }}
